job_queue: sonic-ci
provision_data:
  distro: jammy
test_data:
  test_cmds: |
    set -e
    set -x

    # 1. Install necessary packages
    ssh ubuntu@$DEVICE_IP curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /tmp/docker.gpg > /dev/null
    ssh ubuntu@$DEVICE_IP sudo apt-key add /tmp/docker.gpg
    ssh ubuntu@$DEVICE_IP 'echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu jammy stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null'
    ssh ubuntu@$DEVICE_IP sudo apt update > /dev/null
    ssh ubuntu@$DEVICE_IP sudo apt remove -y containerd > /dev/null
    ssh ubuntu@$DEVICE_IP sudo apt install -y docker-ce python3 python-is-python3 python3-pip pipx curl j2cli make apt-transport-https ca-certificates gnupg-agent software-properties-common > /dev/null
    ssh ubuntu@$DEVICE_IP sudo gpasswd -a ubuntu docker
    ssh ubuntu@$DEVICE_IP sudo systemctl restart docker
    ssh ubuntu@$DEVICE_IP sudo chmod a+rw /var/run/docker.sock

    ssh ubuntu@$DEVICE_IP sudo snap install lxd
    ssh ubuntu@$DEVICE_IP sudo lxd init --minimal
    ssh ubuntu@$DEVICE_IP sudo lxd --version
    ssh ubuntu@$DEVICE_IP sudo systemctl status snap.lxd.daemon.service
    ssh ubuntu@$DEVICE_IP sudo snap install rockcraft --classic
    ssh ubuntu@$DEVICE_IP sudo rockcraft --version

    ssh ubuntu@$DEVICE_IP pip3 install -q --user j2cli > /dev/null
    ssh ubuntu@$DEVICE_IP pip3 install -q --user jinjanator > /dev/null

    # 2. Install the rock-related dependencies
    ssh ubuntu@$DEVICE_IP sudo snap install rockcraft --classic
    ssh ubuntu@$DEVICE_IP lxd init --auto
    ssh ubuntu@$DEVICE_IP sudo sh -c 'echo "net.ipv4.conf.all.forwarding=1" > /etc/sysctl.d/99-forwarding.conf'
    ssh ubuntu@$DEVICE_IP sudo systemctl restart systemd-sysctl
    ssh ubuntu@$DEVICE_IP sudo iptables  -I DOCKER-USER -i lxdbr0 -j ACCEPT
    ssh ubuntu@$DEVICE_IP sudo ip6tables -I DOCKER-USER -i lxdbr0 -j ACCEPT
    ssh ubuntu@$DEVICE_IP sudo iptables  -I DOCKER-USER -o lxdbr0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
    ssh ubuntu@$DEVICE_IP sudo ip6tables -I DOCKER-USER -o lxdbr0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT

    # 3. Build broadcom image (rock)
    ssh ubuntu@$DEVICE_IP git clone -q -b feature_noble_build --recurse-submodules https://github.com/canonical/sonic-buildimage.git > /dev/null
    ssh ubuntu@$DEVICE_IP sudo modprobe overlay
    ssh ubuntu@$DEVICE_IP "cd /home/ubuntu/sonic-buildimage && make init"
    ssh ubuntu@$DEVICE_IP "cd /home/ubuntu/sonic-buildimage && MIRROR_SECURITY_URLS=http://mirror.csclub.uwaterloo.ca/ubuntu/ MIRROR_URLS=http://mirror.csclub.uwaterloo.ca/ubuntu/ make configure PLATFORM=broadcom"
    ssh ubuntu@$DEVICE_IP "cd /home/ubuntu/sonic-buildimage && DBGOPT=1 SONIC_BUILD_RETRY_COUNT=15 make SONIC_BUILD_JOBS=4 -f Makefile.rocks target/sonic-broadcom.bin"

output_timeout: 1800  # 30min
global_timeout: 86400 # 24hours

reserve_data:
  ssh_keys:
    - lp:yanjiangpku
    - gh:jy5275
  timeout: 21600
