name: Build brcm image on feature_noble_build branch

on:
  workflow_dispatch:
  schedule:
    - cron: '0 22 * * *'  # Every day at 22:00 UTC

jobs:
  testflinger-brcm-build-only:
    runs-on: [self-hosted, self-hosted-linux-amd64-jammy-private-endpoint-medium]

    timeout-minutes: 300  # Time limit for this GitHub workflow job (not testflinger job!): 6 hours
    steps:
      - uses: actions/checkout@v4

      - name: Inject branch name into testflinger job
        run: |
          BRANCH="${GITHUB_REF#refs/heads/}"
          sed -i "s|-b feature_noble_build|-b ${BRANCH}|g" ${{ github.workspace }}/.github/testflinger/build_brcm_on_feature_noble_build.yaml
          echo "Using branch: ${BRANCH} for testflinger job"

      - name: Submit job
        id: submit-job
        uses: canonical/testflinger/.github/actions/submit@main
        with:
          poll: true
          job-path: ${{ github.workspace }}/.github/testflinger/build_brcm_on_feature_noble_build.yaml

      - name: Display results
        id: get-results
        run: |
          testflinger results ${{ steps.submit-job.outputs.id }} > results.json
          cat results.json

      - name: Check test status
        run: |
          set -e
          testflinger results ${{ steps.submit-job.outputs.id }} > results.json
          status=$(jq '.test_status' results.json)
          if ! [[ "$status" =~ ^[0-9]+$ ]]; then
            echo "Invalid or missing test_status in results.json"
            exit 1
          fi
          if [ "$status" -ne 0 ]; then
              echo "testflinger task failed with status $status"
              jq -r '.test_output' results.json
              exit 1
          else
              echo "testflinger task succeeded"
          fi
